version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: 3gor-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: 3gor_interior
    volumes:
      - mongodb_data:/data/db
    networks:
      - 3gor-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: 3gor-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      NODE_ENV: production
      CLIENT_URL: http://localhost:3000
      # ✅ Corrected connection string (use admin auth DB)
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/3gor_interior?authSource=admin
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - 3gor-network

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: 3gor-frontend
    restart: always
    ports:
      - "80:3000"
    environment:
      REACT_APP_API_URL: http://backend:5000/api
      REACT_APP_UPLOADS_URL: http://backend:5000/
    depends_on:
      - backend
    networks:
      - 3gor-network

volumes:
  mongodb_data:
    driver: local

networks:
  3gor-network:
    driver: bridge
